# Generated by Django 5.0.4 on 2024-04-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_band_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.DeleteModel(
            name='Vettements',
        ),
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
    ]
