# Generated by Django 5.0.4 on 2024-04-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_band_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vetement', models.CharField(max_length=100)),
                ('id_produit', models.IntegerField(max_length=1000)),
                ('quantite', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vetements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('prix', models.BigIntegerField()),
            ],
        ),
    ]
