# Generated by Django 5.0.4 on 2024-04-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_panier_vetements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='id_produit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vetements',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
