# Generated by Django 5.0.4 on 2024-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier',
            old_name='id_produit',
            new_name='id_client',
        ),
        migrations.AddField(
            model_name='panier',
            name='id_vetement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panier',
            name='nom_client',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
    ]
