# Generated by Django 5.0.4 on 2024-04-22 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_rename_id_produit_panier_id_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.client'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='id_vetement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.vetements'),
        ),
    ]
